# Generated by Django 5.2.17 on 2026-09-07 16:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diente_fdi', models.CharField(blank=True, max_length=2, verbose_name='Diente')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'detalle_factura',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('numero_control', models.CharField(blank=True, help_text='Formato fiscal: 00-NNNNN (auto-generado)', max_length=10, unique=True, verbose_name='Número de control')),
                ('estado', models.CharField(choices=[('emitida', 'Emitida'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='emitida', max_length=15)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('seguro', 'Seguro / HMO')], max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tasa', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Tasa al emitir (Bs/$)')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('motivo_anulacion', models.CharField(blank=True, choices=[('devolucion', 'Devolución al cliente'), ('falta_resultado', 'Falta de resultado'), ('otros', 'Otros')], max_length=20)),
                ('motivo_anulacion_otro', models.TextField(blank=True, verbose_name='Especificar motivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_fecha_act', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'factura',
                'ordering': ['-id'],
            },
        ),
    ]
