# Generated by Django 5.2.17 on 2026-09-07 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_factura', to='clinical.serviciodental'),
        ),
        migrations.AddField(
            model_name='factura',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='clinical.citadental'),
        ),
        migrations.AddField(
            model_name='factura',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='billing.factura'),
        ),
        migrations.AddConstraint(
            model_name='detallefactura',
            constraint=models.UniqueConstraint(fields=('factura', 'servicio', 'diente_fdi'), name='uniq_factura_servicio_diente'),
        ),
    ]
