# Generated by Django 5.2.17 on 2026-09-07 15:49

import apps.core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='LAB CLINICO', max_length=150)),
                ('rif', models.CharField(blank=True, max_length=30, verbose_name='RIF')),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ciudad', models.CharField(blank=True, max_length=80)),
                ('lema', models.CharField(blank=True, max_length=120)),
                ('simbolo_moneda', models.CharField(default='Bs.', max_length=5)),
                ('logo', models.FileField(blank=True, help_text='Se muestra en el encabezado de reportes y facturas en PDF', null=True, upload_to='logo/', validators=[apps.core.models.validar_logo], verbose_name='Logo del laboratorio (PNG, JPG o SVG)')),
                ('bioanalista_nombre', models.CharField(blank=True, max_length=120, verbose_name='Bioanalista para firma')),
                ('bioanalista_registro', models.CharField(blank=True, max_length=40, verbose_name='Nro de registro del bioanalista')),
                ('firma_imagen', models.ImageField(blank=True, help_text='Se imprime sobre la línea de firma en los PDF', null=True, upload_to='firmas/', verbose_name='Firma del bioanalista (PNG transparente)')),
                ('sello_imagen', models.ImageField(blank=True, help_text='Se imprime junto a la firma en los PDF', null=True, upload_to='sellos/', verbose_name='Sello del laboratorio (PNG transparente)')),
            ],
            options={
                'verbose_name': 'Datos del laboratorio',
                'verbose_name_plural': 'Datos del laboratorio',
            },
        ),
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Tasa (Bs por $)')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tasa de cambio',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
