# Generated by Django 5.2.17 on 2026-09-07 17:33

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datoslaboratorio',
            options={'verbose_name': 'Datos de la clínica', 'verbose_name_plural': 'Datos de la clínica'},
        ),
        migrations.AlterField(
            model_name='datoslaboratorio',
            name='bioanalista_nombre',
            field=models.CharField(blank=True, max_length=120, verbose_name='Odontólogo para firma'),
        ),
        migrations.AlterField(
            model_name='datoslaboratorio',
            name='bioanalista_registro',
            field=models.CharField(blank=True, max_length=40, verbose_name='Nro de registro del odontólogo (CO)'),
        ),
        migrations.AlterField(
            model_name='datoslaboratorio',
            name='firma_imagen',
            field=models.ImageField(blank=True, help_text='Se imprime sobre la línea de firma en los PDF', null=True, upload_to='firmas/', verbose_name='Firma del odontólogo (PNG transparente)'),
        ),
        migrations.AlterField(
            model_name='datoslaboratorio',
            name='logo',
            field=models.FileField(blank=True, help_text='Se muestra en el encabezado de reportes y facturas en PDF', null=True, upload_to='logo/', validators=[apps.core.models.validar_logo], verbose_name='Logo de la clínica (PNG, JPG o SVG)'),
        ),
        migrations.AlterField(
            model_name='datoslaboratorio',
            name='sello_imagen',
            field=models.ImageField(blank=True, help_text='Se imprime junto a la firma en los PDF', null=True, upload_to='sellos/', verbose_name='Sello de la clínica (PNG transparente)'),
        ),
    ]
