# Generated by Django 5.2.17 on 2026-09-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_datoslaboratorio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoslaboratorio',
            name='logo',
            field=models.FileField(blank=True, help_text='Se muestra en el encabezado de reportes y facturas en PDF', null=True, upload_to='logo/', verbose_name='Logo de la clínica (PNG, JPG, SVG o WebP)'),
        ),
    ]
