# Generated by Django 5.2.17 on 2026-09-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_datoslaboratorio_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoslaboratorio',
            name='tema',
            field=models.CharField(choices=[('dark', 'Oscuro (actual)'), ('azul', 'Azul degradado'), ('verde', 'Verde degradado'), ('rosa', 'Rosado degradado')], default='dark', max_length=10, verbose_name='Tema de color'),
        ),
    ]
