# Generated by Django 5.2.17 on 2026-09-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_datoslaboratorio_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clinica', models.CharField(default='OdontoClin', max_length=120)),
                ('wa_prefijo', models.CharField(default='58', max_length=5, verbose_name='Prefijo de pais (WhatsApp)')),
                ('plantilla_whatsapp', models.TextField(default='Hola {nombre} 👋 le saluda {clinica}. Le recordamos su cita de {servicio} el {fecha} a las {hora}. Por favor confirme respondiendo SI. ¡Gracias!')),
            ],
            options={
                'verbose_name': 'Configuracion de la clinica',
                'verbose_name_plural': 'Configuracion de la clinica',
            },
        ),
    ]
