# Generated by Django 5.2.17 on 2026-09-07 15:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioDental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_usd', models.DecimalField(decimal_places=2, help_text='Precio en dólares. Se facturará en Bs usando la tasa del día.', max_digits=10, verbose_name='Precio ($)')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servicio dental',
                'db_table': 'servicio_dental',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ExpedienteDental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo de la consulta')),
                ('patologias', models.TextField(blank=True, verbose_name='Patologías detectadas')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias conocidas')),
                ('operaciones', models.TextField(blank=True, verbose_name='Operaciones anteriores')),
                ('notas', models.TextField(blank=True, verbose_name='Notas clínicas')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='expedientes/%Y/%m/', verbose_name='Archivo adjunto (RX/PDF/imagen)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_fecha_act', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_dentales_creados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_dentales', to='patients.paciente')),
            ],
            options={
                'db_table': 'expediente_dental',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='OrdenDental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('anulada', 'Anulada')], default='abierta', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_dentales', to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='clinical.expedientedental')),
            ],
            options={
                'db_table': 'orden_dental',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='OrdenDentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diente_fdi', models.CharField(blank=True, choices=[('11', 'Incisivo central superior derecho'), ('12', 'Incisivo lateral superior derecho'), ('13', 'Canino superior derecho'), ('14', 'Primer premolar superior derecho'), ('15', 'Segundo premolar superior derecho'), ('16', 'Primer molar superior derecho'), ('17', 'Segundo molar superior derecho'), ('18', 'Tercer molar superior derecho'), ('21', 'Incisivo central superior izquierdo'), ('22', 'Incisivo lateral superior izquierdo'), ('23', 'Canino superior izquierdo'), ('24', 'Primer premolar superior izquierdo'), ('25', 'Segundo premolar superior izquierdo'), ('26', 'Primer molar superior izquierdo'), ('27', 'Segundo molar superior izquierdo'), ('28', 'Tercer molar superior izquierdo'), ('31', 'Incisivo central inferior izquierdo'), ('32', 'Incisivo lateral inferior izquierdo'), ('33', 'Canino inferior izquierdo'), ('34', 'Primer premolar inferior izquierdo'), ('35', 'Segundo premolar inferior izquierdo'), ('36', 'Primer molar inferior izquierdo'), ('37', 'Segundo molar inferior izquierdo'), ('38', 'Tercer molar inferior izquierdo'), ('41', 'Incisivo central inferior derecho'), ('42', 'Incisivo lateral inferior derecho'), ('43', 'Canino inferior derecho'), ('44', 'Primer premolar inferior derecho'), ('45', 'Segundo premolar inferior derecho'), ('46', 'Primer molar inferior derecho'), ('47', 'Segundo molar inferior derecho'), ('48', 'Tercer molar inferior derecho'), ('51', 'Incisivo central superior derecho deciduo'), ('52', 'Incisivo lateral superior derecho deciduo'), ('53', 'Canino superior derecho deciduo'), ('54', 'Primer molar superior derecho deciduo'), ('55', 'Segundo molar superior derecho deciduo'), ('61', 'Incisivo central superior izquierdo deciduo'), ('62', 'Incisivo lateral superior izquierdo deciduo'), ('63', 'Canino superior izquierdo deciduo'), ('64', 'Primer molar superior izquierdo deciduo'), ('65', 'Segundo molar superior izquierdo deciduo'), ('71', 'Incisivo central inferior izquierdo deciduo'), ('72', 'Incisivo lateral inferior izquierdo deciduo'), ('73', 'Canino inferior izquierdo deciduo'), ('74', 'Primer molar inferior izquierdo deciduo'), ('75', 'Segundo molar inferior izquierdo deciduo'), ('81', 'Incisivo central inferior derecho deciduo'), ('82', 'Incisivo lateral inferior derecho deciduo'), ('83', 'Canino inferior derecho deciduo'), ('84', 'Primer molar inferior derecho deciduo'), ('85', 'Segundo molar inferior derecho deciduo')], max_length=2, verbose_name='Diente (opcional)')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinical.ordendental')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinical.serviciodental')),
            ],
            options={
                'db_table': 'orden_dental_item',
            },
        ),
        migrations.CreateModel(
            name='HistorialDiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diente_fdi', models.CharField(choices=[('11', 'Incisivo central superior derecho'), ('12', 'Incisivo lateral superior derecho'), ('13', 'Canino superior derecho'), ('14', 'Primer premolar superior derecho'), ('15', 'Segundo premolar superior derecho'), ('16', 'Primer molar superior derecho'), ('17', 'Segundo molar superior derecho'), ('18', 'Tercer molar superior derecho'), ('21', 'Incisivo central superior izquierdo'), ('22', 'Incisivo lateral superior izquierdo'), ('23', 'Canino superior izquierdo'), ('24', 'Primer premolar superior izquierdo'), ('25', 'Segundo premolar superior izquierdo'), ('26', 'Primer molar superior izquierdo'), ('27', 'Segundo molar superior izquierdo'), ('28', 'Tercer molar superior izquierdo'), ('31', 'Incisivo central inferior izquierdo'), ('32', 'Incisivo lateral inferior izquierdo'), ('33', 'Canino inferior izquierdo'), ('34', 'Primer premolar inferior izquierdo'), ('35', 'Segundo premolar inferior izquierdo'), ('36', 'Primer molar inferior izquierdo'), ('37', 'Segundo molar inferior izquierdo'), ('38', 'Tercer molar inferior izquierdo'), ('41', 'Incisivo central inferior derecho'), ('42', 'Incisivo lateral inferior derecho'), ('43', 'Canino inferior derecho'), ('44', 'Primer premolar inferior derecho'), ('45', 'Segundo premolar inferior derecho'), ('46', 'Primer molar inferior derecho'), ('47', 'Segundo molar inferior derecho'), ('48', 'Tercer molar inferior derecho'), ('51', 'Incisivo central superior derecho deciduo'), ('52', 'Incisivo lateral superior derecho deciduo'), ('53', 'Canino superior derecho deciduo'), ('54', 'Primer molar superior derecho deciduo'), ('55', 'Segundo molar superior derecho deciduo'), ('61', 'Incisivo central superior izquierdo deciduo'), ('62', 'Incisivo lateral superior izquierdo deciduo'), ('63', 'Canino superior izquierdo deciduo'), ('64', 'Primer molar superior izquierdo deciduo'), ('65', 'Segundo molar superior izquierdo deciduo'), ('71', 'Incisivo central inferior izquierdo deciduo'), ('72', 'Incisivo lateral inferior izquierdo deciduo'), ('73', 'Canino inferior izquierdo deciduo'), ('74', 'Primer molar inferior izquierdo deciduo'), ('75', 'Segundo molar inferior izquierdo deciduo'), ('81', 'Incisivo central inferior derecho deciduo'), ('82', 'Incisivo lateral inferior derecho deciduo'), ('83', 'Canino inferior derecho deciduo'), ('84', 'Primer molar inferior derecho deciduo'), ('85', 'Segundo molar inferior derecho deciduo')], max_length=2, verbose_name='Diente FDI')),
                ('tipo', models.CharField(choices=[('sano', 'Sano'), ('caries', 'Caries'), ('obstruccion', 'Obturación/empaste'), ('endodoncia', 'Endodoncia'), ('corona', 'Corona'), ('sellante', 'Sellante'), ('extraccion', 'Extracción'), ('protesis', 'Prótesis'), ('implante', 'Implante'), ('ortodoncia', 'Ortodoncia'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de tratamiento')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_dientes', to='clinical.expedientedental')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dientes_historial', to='patients.paciente')),
            ],
            options={
                'db_table': 'historial_diente',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['paciente', 'diente_fdi'], name='historial_d_pacient_2ed293_idx')],
            },
        ),
    ]
