# Generated by Django 5.2.17 on 2026-09-07 16:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioDental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio ($)')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servicio dental',
                'db_table': 'servicio_dental',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ExpedienteDental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patologias', models.TextField(blank=True, verbose_name='Patologías detectadas')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias conocidas')),
                ('operaciones', models.TextField(blank=True, verbose_name='Operaciones anteriores')),
                ('notas', models.TextField(blank=True, verbose_name='Notas generales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_fecha_act', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_dentales_creados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='expediente_dental', to='patients.paciente')),
            ],
            options={
                'db_table': 'expediente_dental',
            },
        ),
        migrations.CreateModel(
            name='CitaDental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo de la consulta')),
                ('notas', models.TextField(blank=True, verbose_name='Notas de la cita')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='citas/%Y/%m/', verbose_name='Archivo adjunto (RX/PDF/imagen)')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada')], default='atendida', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_fecha_act', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas_creadas', to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='clinical.expedientedental')),
            ],
            options={
                'db_table': 'cita_dental',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CitaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diente_fdi', models.CharField(blank=True, choices=[('18', 'Diente 18'), ('17', 'Diente 17'), ('16', 'Diente 16'), ('15', 'Diente 15'), ('14', 'Diente 14'), ('13', 'Diente 13'), ('12', 'Diente 12'), ('11', 'Diente 11'), ('21', 'Diente 21'), ('22', 'Diente 22'), ('23', 'Diente 23'), ('24', 'Diente 24'), ('25', 'Diente 25'), ('26', 'Diente 26'), ('27', 'Diente 27'), ('28', 'Diente 28'), ('38', 'Diente 38'), ('37', 'Diente 37'), ('36', 'Diente 36'), ('35', 'Diente 35'), ('34', 'Diente 34'), ('33', 'Diente 33'), ('32', 'Diente 32'), ('31', 'Diente 31'), ('41', 'Diente 41'), ('42', 'Diente 42'), ('43', 'Diente 43'), ('44', 'Diente 44'), ('45', 'Diente 45'), ('46', 'Diente 46'), ('47', 'Diente 47'), ('48', 'Diente 48'), ('55', 'Diente 55'), ('54', 'Diente 54'), ('53', 'Diente 53'), ('52', 'Diente 52'), ('51', 'Diente 51'), ('61', 'Diente 61'), ('62', 'Diente 62'), ('63', 'Diente 63'), ('64', 'Diente 64'), ('65', 'Diente 65'), ('75', 'Diente 75'), ('74', 'Diente 74'), ('73', 'Diente 73'), ('72', 'Diente 72'), ('71', 'Diente 71'), ('81', 'Diente 81'), ('82', 'Diente 82'), ('83', 'Diente 83'), ('84', 'Diente 84'), ('85', 'Diente 85')], max_length=2, verbose_name='Diente')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinical.citadental')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinical.serviciodental')),
            ],
            options={
                'db_table': 'cita_item',
            },
        ),
        migrations.CreateModel(
            name='HistorialDiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diente_fdi', models.CharField(choices=[('18', 'Diente 18'), ('17', 'Diente 17'), ('16', 'Diente 16'), ('15', 'Diente 15'), ('14', 'Diente 14'), ('13', 'Diente 13'), ('12', 'Diente 12'), ('11', 'Diente 11'), ('21', 'Diente 21'), ('22', 'Diente 22'), ('23', 'Diente 23'), ('24', 'Diente 24'), ('25', 'Diente 25'), ('26', 'Diente 26'), ('27', 'Diente 27'), ('28', 'Diente 28'), ('38', 'Diente 38'), ('37', 'Diente 37'), ('36', 'Diente 36'), ('35', 'Diente 35'), ('34', 'Diente 34'), ('33', 'Diente 33'), ('32', 'Diente 32'), ('31', 'Diente 31'), ('41', 'Diente 41'), ('42', 'Diente 42'), ('43', 'Diente 43'), ('44', 'Diente 44'), ('45', 'Diente 45'), ('46', 'Diente 46'), ('47', 'Diente 47'), ('48', 'Diente 48'), ('55', 'Diente 55'), ('54', 'Diente 54'), ('53', 'Diente 53'), ('52', 'Diente 52'), ('51', 'Diente 51'), ('61', 'Diente 61'), ('62', 'Diente 62'), ('63', 'Diente 63'), ('64', 'Diente 64'), ('65', 'Diente 65'), ('75', 'Diente 75'), ('74', 'Diente 74'), ('73', 'Diente 73'), ('72', 'Diente 72'), ('71', 'Diente 71'), ('81', 'Diente 81'), ('82', 'Diente 82'), ('83', 'Diente 83'), ('84', 'Diente 84'), ('85', 'Diente 85')], max_length=2, verbose_name='Diente FDI')),
                ('tipo', models.CharField(choices=[('sano', 'Sano'), ('caries', 'Caries'), ('obstruccion', 'Obturación/empaste'), ('endodoncia', 'Endodoncia'), ('corona', 'Corona'), ('sellante', 'Sellante'), ('extraccion', 'Extracción'), ('protesis', 'Prótesis'), ('implante', 'Implante'), ('ortodoncia', 'Ortodoncia'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de tratamiento')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dientes', to='clinical.citadental')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dientes_historial', to='patients.paciente')),
            ],
            options={
                'db_table': 'historial_diente',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['paciente', 'diente_fdi'], name='historial_d_pacient_2ed293_idx')],
            },
        ),
    ]
