# Generated by Django 5.2.17 on 2026-09-07 18:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('indicaciones_generales', models.TextField(blank=True, help_text='Indicaciones libres que aplican a toda la receta', verbose_name='Indicaciones generales adicionales')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='clinical.citadental')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'receta',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RecetaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Medicamento')),
                ('dosis', models.CharField(blank=True, max_length=60, verbose_name='Dosis')),
                ('frecuencia', models.CharField(blank=True, max_length=60, verbose_name='Frecuencia')),
                ('duracion', models.CharField(blank=True, max_length=60, verbose_name='Duración')),
                ('indicacion', models.TextField(blank=True, help_text='Si se deja vacía, se genera automáticamente con dosis/frecuencia/duración', verbose_name='Indicación específica')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='clinical.receta')),
            ],
            options={
                'db_table': 'receta_medicamento',
                'ordering': ['id'],
            },
        ),
    ]
