# Generated by Django 5.2.17 on 2026-09-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_receta_recetamedicamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citadental',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada'), ('ausente', 'Ausente')], default='atendida', max_length=15),
        ),
    ]
