# Generated by Django 5.2.17 on 2026-09-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre comercial')),
                ('slug', models.SlugField(help_text='Subdominio (ej: dientesano → dientesano.facdin.com)', max_length=63, unique=True, verbose_name='Subdominio')),
                ('tunnel_id', models.CharField(blank=True, max_length=100, verbose_name='Tunnel ID')),
                ('token', models.TextField(blank=True, verbose_name='Token de instalación')),
                ('estado', models.CharField(choices=[('creando', 'Creando túnel'), ('activo', 'Activo'), ('suspendido', 'Suspendido'), ('error', 'Error')], default='creando', max_length=20, verbose_name='Estado')),
                ('cliente_nombre', models.CharField(blank=True, max_length=150, verbose_name='Nombre del contacto')),
                ('cliente_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del contacto')),
                ('cliente_telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_activacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultimo_check', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
