# Generated by Django 5.2.17 on 2026-09-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='tipo_producto',
            field=models.CharField(choices=[('odontoclin', 'OdontoClin'), ('labclin', 'LabClin')], default='odontoclin', max_length=15, verbose_name='Producto'),
        ),
    ]
