# Generated by Django 5.2.17 on 2026-09-07 15:28

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('ci', models.CharField(blank=True, max_length=30, null=True, verbose_name='CI')),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], max_length=1)),
                ('fecha_nac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_fecha_act', models.DateTimeField(auto_now=True)),
                ('representante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representados', to='patients.paciente', verbose_name='Representante legal')),
            ],
            options={
                'db_table': 'paciente',
                'permissions': [('crear_paciente', 'Crear paciente')],
                'indexes': [models.Index(fields=['apellidos', 'nombres'], name='paciente_apellid_ee766d_idx'), models.Index(fields=['ci'], name='paciente_ci_13f149_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('ci'), condition=models.Q(('ci__isnull', False)), name='paciente_ci_lower_unique'), models.UniqueConstraint(django.db.models.functions.text.Lower('telefono'), condition=models.Q(('telefono__isnull', False)), name='paciente_telefono_lower_unique'), models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email__isnull', False)), name='paciente_email_lower_unique')],
            },
        ),
    ]
